# Based on https://github.com/dgerosa/writeapaper/blob/main/.github/workflows/writeapaper.yml

name: compile-latex
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_proposal:
    runs-on: ubuntu-latest
    env:
      FILE: proposal.pdf
      DIR: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install texlive
        run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      - name: Build LaTeX
        run: cd ${{env.DIR}} && make artifacts
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.FILE}}
          path: artifacts
  deploy:
    needs: [build_proposal]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: gh_pages
          force_orphan: true
